GRPC_PORT: "50051"
GRPC_HOST: "0.0.0.0"
REST_PORT: "8081"
REST_HOST: "0.0.0.0"

USER_SERVICE_ADDR:    "localhost:50052"
PAYMENT_SERVICE_ADDR: "localhost:50053"

POSTGRES:
  POSTGRES_HOST: "localhost"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "root"
  POSTGRES_PASS: "1234"
  POSTGRES_DB:   "rooms"
